apiVersion: v1
kind: Pod
metadata:
  name: jumpbox
spec:
  containers:
  - name: jumpbox
    image: jumpbox-image:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep infinity; done"]
    imagePullPolicy: Never
    ports:
    - containerPort: 80
